## Put comments here that give an overall description of what your
## functions do

## A function that generates a matrix so its inverse can be cached.

makeCacheMatrix <- function(x = matrix()) {
  im <- NULL
  set <- function(b){
    ## First time I use '<<-' which assigns a value to an object outside current environment.
    x <<- b
    im <<- NULL
  }
  get <- function() x
  setim = function(inverse) im <<- inverse
  getim = function() im
  list(set=set, get=get, setim=setim, getim=getim)
}


## A function that checks if the inverse is generated, if not, then computes the inverse of the matrix generated by makeCacheMatrix.

cacheSolve <- function(x, ...) {
  im = x$getim()
  if (!is.null(im)){
    message("retrieving cache data")
    return(im)
  }
  mdata = x$get()
  im = solve(mdata, ...)
  x$setim(im)
  return(im)
}
